### ISSUE TITLE
composer 套件 psr/log 支援 2.0 or 3.0？

### ISSUE THREAD

**Issue by leonjbc** [104corp/php-support#2]
因 [monolog3](https://github.com/Seldaek/monolog/blob/main/composer.json#L17C9-L17C34) 至少需要  psr/log 2 or 3 , 不知有可能更新嗎？
不過 [psr/log 2](https://packagist.org/packages/psr/log#2.0.0) 最低要求使用 PHP8， 這可能影響產品支援 
thank you!

**Comment by MilesChou** [comment]
可以，已定 2.0.0 版
